config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: "users/registrations" }
  
  root to: "home#index"
  resources :users, only: [:index, :show, :new] do
    resources :groups, only: [:new, :create, :show, :index, :destroy]
    resources :entities, only: [:new, :create, :index, :show, :destroy]
  end

  # Logout
  get 'logout', to: 'sessions#destroy', as: 'logout'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  has_many :entities_groups, dependent: :destroy
  has_many :groups, through: :entities_groups, dependent: :destroy

  # Valudation
  validates :name, presence: true, length: { minimum: 2 }
  validates :amount, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/entity_group.rb
class EntityGroup < ApplicationRecord
  belongs_to :group
  belongs_to :entity
end

app/models/group.rb
class Group < ApplicationRecord
  include ImageUploader::Attachment(:icon)

  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :entities_groups, dependent: :destroy
  has_many :entities, through: :entities_groups, dependent: :destroy

  validates :name, presence: true, length: { minimum: 3, too_short: 'Group name
  must be more than 3 characters long' }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :name, presence: true, length: { in: 3..50 }
  validates :email, presence: true
  validates :password, presence: true

  # Associations
  has_many :entities, dependent: :destroy
  has_many :groups, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Go to page after login
  def after_sign_in_path_for(_resource)
    user_groups_url(current_user.id)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up, keys: %i[name email password confirm_password]
    )
    devise_parameter_sanitizer.permit(
      :sign_in, keys: %i[email password]
    )
  end
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :authenticate_user!

  # GET /entities or /entities.json
  def index
    @transactions = Entity.all
    @categories = Group.all
  end

  # GET /entities/1 or /entities/1.json
  def show
    # Transactions per category
    @group_id = params[:id]
    @transactions_per_group = Entity.where(group_id: @group_id).order(created_at: :desc)
    @category_name = Group.find(@group_id).name

    # Sum of amount of transactions in each category
    @sum = Entity.where(group_id: @group_id).sum(:amount)
  end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(author_id: current_user.id, **entity_params)

    respond_to do |format|
      if @entity.save
        format.html { redirect_to user_groups_url, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    if @entity.destroy
      respond_to do |format|
        format.html { redirect_to user_entities_url, notice: 'Entity was successfully destroyed.' }
      end
    else
      puts 'Not deleted'
      flash.now[:error] = "Oops. Couldn't delete entity."
    end
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit(:name, :amount, :group_id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!

  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups
  def index
    @groups = Group.all
  end

  # GET /groups/1
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # POST /groups
  def create
    @group = Group.new(author_id: current_user.id, **group_params)

    respond_to do |format|
      if @group.save
        format.html do
          redirect_to user_groups_url(current_user),
                      notice: 'Group was successfully created.'
        end
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    reset_session
    redirect_to root_path
  end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  protected

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
    user_groups_path(current_user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show; end

  # GET /users/new
  def new
    @user = User.new
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_groups_url(current_user), notice: 'User was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_user
    @user = User.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= entity.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Amount:</strong>
    <%= entity.amount %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this entity", user_entity_path(current_user, entity), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/entities/_form.html.erb
<%= form_with model: entity, url: user_entities_path, class: "contents" do |form| %>
  <% if entity.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, class: "", placeholder: "Name" %>
  </div>

  <div class="field">
    <%= form.text_field :amount, class: "", placeholder: "Amount" %>
  </div>

  <div class="field">
    <p>Categories</p>
    <%= form.select :group_id, options_from_collection_for_select(Group.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.submit "Save", class: "submit" %>
  </div>
<% end %>

app/views/entities/index.html.erb
<div class="category-transactions">
  <div class="transactions-header">
    <div class="transactions-header-menu">
      <%= image_tag("hamburger.png", :alt => "Menu Btn") %>
      <P class="">CATEGORIES</p>
      <%= image_tag("search.png", :alt => "Search") %>
    </div>
  </div>
  <div class="category-transactions-details">
    <h2 class="border bg-blue-50">Categories</h2>
    <% @categories.each do |category| %>
      <div class="category-transactions-details-info">
        <%= link_to user_entity_path(current_user, category) do %>
          <p><%= category.name %></p>
          <p><%= category.icon_data %></p>
        <% end %>
      </div>
    <% end %>
    <p>
      <%= link_to 'New entity', new_user_entity_path,
      class: "border rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
    </p>

    <p><%= link_to 'Back', user_groups_url %></p>
  </div>
</div>

app/views/entities/new.html.erb
<div class="add-transaction-page">
  <div class="transactions-header">
    <div class="transactions-header-menu">
      <%= image_tag("hamburger.png", :alt => "Menu Btn") %>
      <p class="">ADD TRANSACTION</p>
      <%= image_tag("search.png", :alt => "Search") %>
    </div>
  </div>

  <%= render "form", entity: @entity %>
  <div class="back-to-groups">
    <%= link_to 'Back to transactions', user_groups_path(current_user) %>
  </div>
</div>

app/views/entities/show.html.erb
<div class="transactions-page">
  <div class="transactions-header">
    <div class="transactions-header-menu">
      <%= image_tag("hamburger.png", :alt => "Menu Btn") %>
      <P class="">TRANSACTIONS</p>
      <%= image_tag("search.png", :alt => "Search") %>
    </div>
    <div class="transactions-header-cats">
      <p>Most recent</p>
      <p>Most acient</p>
    </div>
  </div>
  <% if @transactions_per_group.empty? %>
    <p>No transactions available.</p>
  <% else %>
    <div class="transactions-details">
      <div class="txn-name-sum">
        <p class="category-name"><%= @category_name.upcase %></p>
        <p>$<%= @sum %></p>
      </div>
      <% @transactions_per_group.each do |tx| %>
        <div class="transactions-info">
          <div class="transaction-icon">
            <%= image_tag "transaction.png", :alt => "Transactions" %>
          </div>
          <div class="name-date-amount">
            <div class="name-date">
              <p><%= tx.name %></p>
              <p class="amount">$<%= tx.amount %></p>
            </div>
            <p><%= tx.created_at.to_date %></p>
          </div>
        </div>
      <% end %>
    </div>
  <% end %>
  <div class="add-transaction">
  <%= link_to "Add Transaction", new_user_entity_path(current_user) %>
  </div>
  <div class="back_to_transactions_btn">
    <%= link_to "Back to categories", user_groups_path(current_user) %>
  </div>

  <div class="scan">
    <p>SCAN</p>
  </div>
</div>

app/views/groups/_form.html.erb
<%= form_with model: group, url: user_groups_path, class: "contents" do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.text_field :name, class: "", placeholder: "Name" %>
  </div>

  <div class="my-5">
    <p>Category Icon</p>
    <%= image_tag form.object.icon_url if form.object.cached_icon_data %>
    <%= form.hidden_field :icon, value: form.object.cached_icon_data %>
    <%= form.file_field :icon %>
  </div>

  <div class="inline">
    <%= form.submit "Save", class: "add-category-btn" %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= group.name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Icon:</strong>
    <%= image_tag group.icon_url if group.icon %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this group", user_group_path(current_user, group), class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/groups/index.html.erb
<div class="categories">
  <div class="categories-header">
    <%= image_tag("hamburger.png", :alt => "Menu Btn ") %>
    <h3 class="font-bold text-4xl">CATEGORIES</h3>
  </div>

  <div id="groups" class="categories-list">
    <% if notice.present? %>
      <div class="notice-container">
        <p class="notice" id="notice"><%= notice %></p>
      </div>
    <% end %>
    <% if @groups.empty? %>
      <p class="no-categories">No categories available</p>
    <% else %>
        <% @groups.each do |group| %>
          <div class="category">
            <%= link_to user_entity_path(current_user.id, group.id) do %>
              <p class="icon">
                <%= image_tag group.icon_url if group.icon %>
              </p>
              <div class="category-details">
                <h4 class="categories-name">
                  <%= group.name.upcase %>
                  <%= @sum_per_category %>
                </h4>
                <p class="category-date-created">
                  <%= group.created_at.to_date %>
                </p>
              </div>
            <% end %>
          </div>
        <% end %>
    <% end %>
    <div class="add-category">
      <%= link_to 'Add Category', new_user_group_path, class: "" %>
    </div>
  </div>


</div>

app/views/groups/new.html.erb
<div class="add-category-page">
  <div class="transactions-header">
    <div class="transactions-header-menu">
      <%= image_tag("hamburger.png", :alt => "Menu Btn") %>
      <P class="">ADD CATEGORY</p>
      <%= image_tag("search.png", :alt => "Search") %>
    </div>
  </div>

  <%= render "form", group: @group %>
  <div class="back-to-groups">
    <%= link_to 'Back to groups', user_groups_path %>
  </div>
</div>

app/views/groups/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @group %>

    <div class="inline-block ml-2">
      <%= button_to 'Destroy this group',
        user_group_path(current_user.id, @group.id), method: :delete,
        class: "mt-2 py-3 px-5 bg-gray-100 font-medium border rounded-md"
      %>
    </div>
    <%= link_to 'Back to groups', user_groups_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>

app/views/home/index.html.erb
<div class="home-page">
  <p class="home-header">BUDGET</p>

  <div class="home-btns">
    <p class="login-btn"><%= link_to 'LOG IN', new_user_session_path %></p>
    <p class="registration-btn"><%= link_to 'SIGN UP', new_user_registration_path %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Budget</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>